// <auto-generated />
using System;
using CreditRisk.CreditAnalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditRisk.CreditAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(CreditAnalysisDbContext))]
    [Migration("20260902125351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditRisk.CreditAnalysis.Domain.Entities.CreditProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ProposalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proposal_type");

                    b.Property<string>("Rating")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("risk_rating");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_manual_review");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_credit_proposals_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_credit_proposals_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_credit_proposals_status");

                    b.ToTable("credit_proposals", (string)null);
                });

            modelBuilder.Entity("CreditRisk.CreditAnalysis.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("document");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_income");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_document");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("CreditRisk.Shared.Kernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_outbox_processed_at");

                    b.HasIndex("ScheduledAt", "ProcessedAt")
                        .HasDatabaseName("idx_outbox_unprocessed");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("CreditRisk.CreditAnalysis.Domain.Entities.CreditProposal", b =>
                {
                    b.OwnsOne("CreditRisk.Shared.Kernel.ValueObjects.MoneyAmount", "ApprovedLimit", b1 =>
                        {
                            b1.Property<Guid>("CreditProposalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("approved_limit");

                            b1.HasKey("CreditProposalId");

                            b1.ToTable("credit_proposals");

                            b1.WithOwner()
                                .HasForeignKey("CreditProposalId");
                        });

                    b.OwnsOne("CreditRisk.Shared.Kernel.ValueObjects.MoneyAmount", "RequestedLimit", b1 =>
                        {
                            b1.Property<Guid>("CreditProposalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("requested_limit");

                            b1.HasKey("CreditProposalId");

                            b1.ToTable("credit_proposals");

                            b1.WithOwner()
                                .HasForeignKey("CreditProposalId");
                        });

                    b.Navigation("ApprovedLimit");

                    b.Navigation("RequestedLimit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
