<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CreditRisk.Operations.Client</AssemblyName>
    <RootNamespace>CreditRisk.Operations.Client</RootNamespace>
    <PublishAot>false</PublishAot>
    <NoWarn>$(NoWarn);MUD0001;MUD0002;CA2007;CA1063;CA1816;CA1031;CA1003;CA1716;CA1822;CA1308</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="MudBlazor" Version="7.15.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../shared/CreditRisk.Shared.Contracts/CreditRisk.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
